#
###################################
# Site wide configuration
####################################
#
title:       "Catatan Sasongko"
description: "Catatan Penggunaan Open Source"
url:        # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Jakarta
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:year/:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Sasongko Bawono
  avatar: 
  job: "Pelajar/Student"
  bio: "Slackware user & open source enthusiast"
  email: sasongko262@gmail.com
  telegram: sakawn10
  disqus-shortname: catatansasongko
  twitter:
  facebook: 
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sasongko26
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: sasongko42
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
